### ISSUE TITLE
Logic triggers for visibility and validations?

### ISSUE THREAD

**Issue by rikkipitt** [kelp404/angular-form-builder#17]
I was wondering if you had any plans (or advice) for creating a trigger section for fields?

An example would be if a select box equals, is greater than, less than etc another field then do this (could be show or hide another field or change validations).

Looking forward to hearing your advice @kelp404, cheers for the project so far - it's great!

Rikki

**Comment by kamleshpawar2006** [comment]
Hello Kelp,
i tried this 
$validator.validate($scope, 'default') 
but it is showing this error:
TypeError: Cannot read property '$$hashKey' of undefined

How can i trigger validation messages on a button click?
Thanks for the great plugin :)
