### ISSUE TITLE
For saving people's life, please make form pre-population easier.

### ISSUE THREAD

**Issue by 18601673727** [kelp404/angular-form-builder#39]
I was trying to pre-populate the form which already had values(saved in database) as you said in another issue, fetching data through `$http` then put it to `$scope`. But I don't understand which variable/object of the `$scope` should been put, I assumed `$scope.input` and `$scope.defaultValue`.

Here is my test of each one:

> Use `$scope.input` nothing happened.
> Use `$scope.defaultValue` works fine but failed when form component is checkbox.

So I suggest that we shall not keep arrays like this `['value1', 'value2', 'value3']` in the $scope.input when creating forms, the checkbox component cannot use it directly, and it was horrible to check each component of the form is a checkbox, and it is hard to do form feedback statistics, right? Just use the id of component's option instead, like this:

```
[
  {"optionId": "1", "checked": "true"},
  {"optionId": "2", "checked": "false"}
]
```

then we can retrieve/store a more structural data, at least, use `[true, false]` please.

Thanks very much for sharing such a good project.

**Comment by vko-online** [comment]
@kelp404 Poor response. Single demo with data population, would be good.

**Comment by darrencauthon** [comment]
> Poor response.

![haha](https://cloud.githubusercontent.com/assets/148768/10224424/6efd01d4-6823-11e5-91df-03413653e05e.png)
