### ISSUE TITLE
Formbuilder drag and drop re-ordering losing existing components upon second (or more) instantiation of the $builder

### ISSUE THREAD

**Issue by lstone** [kelp404/angular-form-builder#59]
I use the $builder to create form templates in my application. My application has a form template listing landing page and you can click on a form there to edit it.

If I launch my application and edit one form and then close that form and return to the list page - and then open a second form to edit - the drag and drop functionality "loses" components when re-ordering.

Expected result:
1. go to form template listing page
2. choose a form to edit
3. begin editing that form by dragging components to drop zone.
4. save form and return to listing page
5. choose a different form to edit
6. RE-ORDER components
7. components re-order appropriately

Actual result: 
1. go to form template listing page
2. choose a form to edit
3. begin editing that form by dragging components to drop zone.
4. save form and return to listing page
5. choose a different form to edit
6. RE-ORDER components
7. upon re-ordering a component multiple already chosen components "disappear" from the form.

This only happens when you visit a second form. The first re-order attempt always works as expected. I would love any help. Thank you so much. I'm lost here.

PS: Perhaps this is an issue where the form builder having been instantiated twice loses scope? Is there a "reset" mechanism for the form that I can use to force reset?

**Comment by bogdancochioras** [comment]
in angular-form-builder.js in the method "isHover" definition offsetB.top sometimes is 0 for no reason adding a validation :
  if(offsetB.top == 0)
          return true;
before:
 return isHover.x && isHover.y;
solved the issue for me.

**Comment by huei90** [comment]
@darrencauthon Why laughing
