### ISSUE TITLE
popup is not working in chrome browser thought its working fine in firefox and IE

### ISSUE THREAD

**Issue by joezhouOxford** [kelp404/angular-form-builder#81]
Does this happen to anymore else?
I tested with http://kelp404.github.io/angular-form-builder/ and it is the same

**Comment by pessotti** [comment]
Sometimes it happens to me too... And it lasts until a full reboot, even if I close Google Chrome it doesn't work after opening again.

As a workaround, I'm trying to place a button to manually open the popup just in case. If anyone knows how to do it, I would be glad to know!

**Comment by pessotti** [comment]
I think I have found the bug. Google Chrome fires both mousemouve AND mouseclick when clicking something. When this happens, the popover doesnt open because it thinks we are trying to move a field.

**Comment by pessotti** [comment]
I have solved this bug by storing the mouseX and Y, comparing it every time the mouse move around.

Add the following variables after "this.mouseMoved = false;":

this.mx=0;
this.my=0;

And modify the mousemove handler as below:

$(document).on('mousemove', function(e) {
  if(e.pageX == _this.mx && e.pageY == _this.my)
	return;
  _this.mx = e.pageX;
  _this.my = e.pageY;
  var func, key, _ref;
  _this.mouseMoved = true;
  _ref = _this.hooks.move;
  for (key in _ref) {
	func = _ref[key];
	func(e);
  }
});

**Comment by joezhouOxford** [comment]
thanks pesootti. Your solution works!

**Comment by northoutIshan** [comment]
Thanks Pessoti. It works.

**Comment by vrajroham** [comment]
+1

**Comment by itsovereasy** [comment]
Thanks @Pessotti. It really works.
