### ISSUE TITLE
Accessing field values

### ISSUE THREAD

**Issue by StuartMorris** [kelp404/angular-form-builder#82]
I'm creating a form using the drag-and-drop interface from the example to generate a JSON string in an administrator form designer view.

Later, when a user is to fill out the form, I'm using $builder to recreate the form from the JSON string.  What I don't understand is how to access the value(s) inside those fields.  I see that an ng-model=inputText (or inputArray) is applied when the form is rendered.  How do you access those values?  I don't see anything on the $builder.forms['myforms'] object where I expected these to be.

**Comment by kamleshpawar2006** [comment]
Hello StuartMorris,
Have you got the solution for this??
