### ISSUE TITLE
Wat to add new tags

### ISSUE THREAD

**Issue by vishalpachpande** [kelp404/angular-form-builder#85]
Hi I wanted to add file upload tag in this ,so that user can add images ,where should I add that file tag so that I may work.

**Comment by huei90** [comment]
custom yourself by registering a new component
https://github.com/kelp404/angular-form-builder#registercomponent

**Comment by vishalpachpande** [comment]
Hey hi thanks for above help can you give me  some example so that I can get more clear idea about it.

**Comment by huei90** [comment]
We can see some example here
https://github.com/kelp404/angular-form-builder/tree/master/example

Try finding the registerComponent.

**Comment by vishalpachpande** [comment]
Thanks :)

**Comment by vishalpachpande** [comment]
hey hi Huei I have register new html element in every register component object but still not working????

**Comment by vishalpachpande** [comment]
hey tnks for the guidance it worked for me.. :)

**Comment by huei90** [comment]
:+1: you can paste your code here to share with others having the same problem.

**Comment by vishalpachpande** [comment]
$builderProvider.registerComponent('Upload image', {
        group: 'Default',
        label: 'Upload image',
        description: 'description',
        placeholder: 'placeholder',
        required: false,
        template: "<div class=\"form-group \">\n    <label for=\"{{formName+index}}\" class=\"col-sm-4 control-label\" ng-class=\"{'fb-required':required}\">{{label}}</label>\n    <div class=\"col-sm-8 uploadImageDiv\">\n        <input type=\"file\" ng-model=\"inputText\" class=\"imageType\" validator-required=\"{{required}}\" validator-group=\"{{formName}}\" id=\"{{formName+index}}\" class=\"form-control\"  placeholder=\"{{placeholder}}\"/>\n        <p class='help-block'>{{description}}</p>\n    </div>\n</div>",
        popoverTemplate: "<form>\n    <div class=\"form-group\">\n        <label class='control-label'>Label</label>\n        <input type='text' ng-model=\"label\" validator=\"[required]\" class='form-control'/>\n    </div>\n    <div class=\"form-group\">\n        <label class='control-label'>Description</label>\n        <input type='text' ng-model=\"description\" class='form-control'/>\n    </div>\n    <div class=\"form-group\">\n        <label class='control-label'>Placeholder</label>\n        <input type='text' ng-model=\"placeholder\" class='form-control'/>\n    </div>\n    <div class=\"checkbox\">\n        <label>\n            <input type='checkbox' ng-model=\"required\" />\n            Required</label>\n    </div>\n\n    <hr/>\n    <div class='form-group'>\n        <input type='submit' ng-click=\"popover.save($event)\" class='btn btn-primary' value='Save'/>\n        <input type='button' ng-click=\"popover.cancel($event)\" class='btn btn-default' value='Cancel'/>\n        <input type='button' ng-click=\"popover.remove($event)\" class='btn btn-danger' value='Delete'/>\n    </div>\n</form>"
      });

**Comment by vishalpachpande** [comment]
In above code you can place html tag which you wanted to customly   add.

**Comment by vishalpachpande** [comment]
hey huei90 I need some more help actually i wanted to remove that "Name" labeled  element which we cant edit or start its editing too
 .

**Comment by huei90** [comment]
please format your code using markdown @vishalpachpande

**Comment by minu-aswanth** [comment]
@vishalpachpande, Were you able to upload images to the server

**Comment by minu-aswanth** [comment]
@vishalpachpande How did you achieve uploading images to the server?

**Comment by vishalpachpande** [comment]
hi,
What you exactly want to do Minu

On Thu, Aug 13, 2015 at 10:37 AM, Minu Aswanth <notifications@github.com>
wrote:

> @vishalpachpande <https://github.com/vishalpachpande>, Were you able to
> upload images to the server
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kelp404/angular-form-builder/issues/85#issuecomment-130536827>
> .
>



-- 

*Thanks and Regards*

*Vishal Pachpande,*
*Software Engineer* | *TechNex Technologies Pvt. Ltd.|* Cell: +91
8793373567  |TechNex Technologies Pvt. Ltd | Home <http://www.tnex.co.in/> |
Pune| India

**Comment by minu-aswanth** [comment]
I want to create a field to upload files @vishalpachpande

**Comment by huei90** [comment]
@vishalpachpande You can beautify your code using markdown language, and everyone can view it.

**Comment by vishalpachpande** [comment]
hi,
sorry for replying late ,simply open component builder and and register
your element overthere it will functional immediately

On Fri, Aug 14, 2015 at 7:27 AM, Minu Aswanth <notifications@github.com>
wrote:

> I want to create a field to upload files @vishalpachpande
> <https://github.com/vishalpachpande>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kelp404/angular-form-builder/issues/85#issuecomment-130918742>
> .
>



-- 

*Thanks and Regards*

*Vishal Pachpande,*
*Software Engineer* | *TechNex Technologies Pvt. Ltd.|* Cell: +91
8793373567  |TechNex Technologies Pvt. Ltd | Home <http://www.tnex.co.in/> |
Pune| India
